import fs from "node:fs";
import path from "node:path";

import { extractJiraPayload } from "@/lib/jira/extract";
import type { JiraEmitPayload } from "@/lib/jira/types";
import { cosmicMarkdown } from "@/lib/six-d/cosmic/markdown";
import { bundleMarkdown } from "@/lib/six-d/markdown";
import type { CosmicRun } from "@/lib/six-d/cosmic";
import { DATA_DIR } from "@/lib/store/paths";

export type SpecDocFiles = {
  dir: string;
  epicStories: string;
  fullSpec: string;
  paths: {
    epicStories: string;
    fullSpec: string;
  };
};

export function epicStoriesMarkdown(payload: JiraEmitPayload): string {
  const L: string[] = [];
  L.push(`# Epic: ${payload.epic.title}`);
  L.push("");
  L.push(`**Initiative:** ${payload.initiativeId}`);
  L.push(`**Spec receipt:** \`${payload.specReceipt}\``);
  L.push(`**COSMIC run:** \`${payload.cosmicRunHash}\``);
  L.push("");
  L.push("## Epic description");
  L.push("");
  L.push(payload.epic.description);
  L.push("");
  L.push("## Stories");
  L.push("");

  for (let i = 0; i < payload.stories.length; i++) {
    const s = payload.stories[i]!;
    L.push(`### ${i + 1}. ${s.title}`);
    L.push("");
    L.push(`**ID:** \`${s.storyId}\``);
    if (s.estimate) L.push(`**Estimate:** ${s.estimate}`);
    if (s.labels.length) L.push(`**Labels:** ${s.labels.join(", ")}`);
    if (s.dependsOn.length) L.push(`**Depends on:** ${s.dependsOn.join(", ")}`);
    L.push("");
    L.push(s.description);
    L.push("");
    if (s.acceptanceCriteria.length) {
      L.push("**Acceptance criteria:**");
      for (const ac of s.acceptanceCriteria) {
        L.push(`- ${ac}`);
      }
      L.push("");
    }
  }

  L.push("---");
  L.push("*Generated by LOOPER — verification-first spec → ticket-ready slices.*");
  return L.join("\n");
}

export function fullSpecMarkdown(run: CosmicRun): string {
  const bundle = bundleMarkdown(run.manifest);
  const cosmic = cosmicMarkdown(run);
  return `${bundle}\n\n---\n\n${cosmic}`;
}

export function writeSpecDocs(
  run: CosmicRun,
  initiativeId: string,
  specReceipt: string,
  emitHash: string,
): SpecDocFiles {
  const payload = extractJiraPayload(run, initiativeId, specReceipt);
  if (!payload) {
    throw new Error("Distribute phase produced no epic or stories — cannot write docs");
  }

  const epicStories = epicStoriesMarkdown(payload);
  const fullSpec = fullSpecMarkdown(run);
  const dir = path.join(DATA_DIR, "spec-docs", `${initiativeId}-${emitHash.slice(0, 16)}`);
  fs.mkdirSync(dir, { recursive: true });

  const epicPath = path.join(dir, "epic-stories.md");
  const fullPath = path.join(dir, "full-spec.md");
  fs.writeFileSync(epicPath, epicStories, "utf8");
  fs.writeFileSync(fullPath, fullSpec, "utf8");

  return {
    dir,
    epicStories,
    fullSpec,
    paths: { epicStories: epicPath, fullSpec: fullPath },
  };
}